spring:
  application:
    name: leader_selection

leaderSelection:
  fixedDelay: ${LEADER_FIXED_DELAY:5000}
  initialDelay:  ${LEADER_INITIAL_DELAY:5000}
  heartBeatThreshold: ${LEADER_HEARTBEAT_THRESHOLD:30000}

someOtherProcessor:
  fixedDelay: ${OTHER_FIXED_DELAY:2000}
  initialDelay:  ${OTHER_INITIAL_DELAY:5000}